#!/bin/bash
# Automatically generated file by generate_files.sh
# Script by gabry3795 - gabry.gabry <at> hotmail.it

adb pull system/ons.bin /proprietary/system
adb pull system/bin/hdmi_daemon /proprietary/system/bin
adb pull system/bin/hwpged /proprietary/system/bin
adb pull system/bin/hwnff /proprietary/system/bin
adb pull system/bin/thermal-daemon /proprietary/system/bin
adb pull system/bin/gps4752logd /proprietary/system/bin
adb pull system/bin/glgps4752 /proprietary/system/bin
adb pull system/bin/rild /proprietary/system/bin
adb pull system/bin/device_monitor /proprietary/system/bin
adb pull system/bin/hw_ueventd /proprietary/system/bin
adb pull system/bin/glgps47531cl /proprietary/system/bin
adb pull system/bin/gpslogd /proprietary/system/bin
adb pull system/bin/glgps4752cl /proprietary/system/bin
adb pull system/bin/mac_addr_normalization /proprietary/system/bin
adb pull system/bin/glgps47531 /proprietary/system/bin
adb pull system/bin/gpsdaemon /proprietary/system/bin
adb pull system/bin/storedefaultkey /proprietary/system/bin
adb pull system/bin/hdb /proprietary/system/bin
adb pull system/bin/atcmdserver /proprietary/system/bin
adb pull system/bin/hw_cdmamodem_service /proprietary/system/bin
adb pull system/bin/hwnffserver /proprietary/system/bin
adb pull system/bin/huawei_tp_test /proprietary/system/bin
adb pull system/lib/libhwextdevice.so /proprietary/system/lib
adb pull system/lib/libCameraHwParam.so /proprietary/system/lib
adb pull system/lib/libcamera_drv.so /proprietary/system/lib
adb pull system/lib/libhuawei_mmi_test.so /proprietary/system/lib
adb pull system/lib/libbalong_audio_ril.so /proprietary/system/lib
adb pull system/lib/libaudioflinger.so /proprietary/system/lib
adb pull system/lib/lib_hwnsd_input.so /proprietary/system/lib
adb pull system/lib/libaudioflinger.huawei.so /proprietary/system/lib
adb pull system/lib/libhuaweiprocessing.so /proprietary/system/lib
adb pull system/lib/lib_hwnsd_sf.so /proprietary/system/lib
adb pull system/lib/libhwouc_jni.so /proprietary/system/lib
adb pull system/lib/libhuaweiaudioalgoservice.so /proprietary/system/lib
adb pull system/lib/libHW_Pano_f.so /proprietary/system/lib
adb pull system/lib/libHwMotionRecognition.so /proprietary/system/lib
adb pull system/lib/libhwtheme_jni.so /proprietary/system/lib
adb pull system/lib/libbalong-ril.so /proprietary/system/lib
adb pull system/lib/libfingersense.so /proprietary/system/lib
adb pull system/lib/libion.so /proprietary/system/lib
adb pull system/lib/libcameraservice.so /proprietary/system/lib
adb pull system/lib/libhwgl.so /proprietary/system/lib
adb pull system/lib/libCameraHwCallBack.so /proprietary/system/lib
adb pull system/lib/libaudioom.so /proprietary/system/lib
adb pull system/lib/libhisi_efuse.so /proprietary/system/lib
adb pull system/lib/libHwManufactureCustEx_jni.so /proprietary/system/lib
adb pull system/lib/libhuaweiaudioeffectutil.so /proprietary/system/lib
adb pull system/lib/libhwaps.so /proprietary/system/lib
adb pull system/lib/libgnuexif.so /proprietary/system/lib
adb pull system/lib/libcamera_client.so /proprietary/system/lib
adb pull system/lib/libgui.so /proprietary/system/lib
adb pull system/lib/libjpu.so /proprietary/system/lib
adb pull system/lib/libHW_BShutter.so /proprietary/system/lib
adb pull system/lib/libhuaweigpsrpc.so /proprietary/system/lib
adb pull system/lib/libHWExtDeviceService.so /proprietary/system/lib
adb pull system/lib/libconfig_interface.so /proprietary/system/lib
adb pull system/lib/libbalong-ril-1.so /proprietary/system/lib
adb pull system/lib/libtfa9887.so /proprietary/system/lib
adb pull system/lib/libhwui.so /proprietary/system/lib
adb pull system/lib/libjpegenchw.so /proprietary/system/lib
adb pull system/lib/libcamera_core.so /proprietary/system/lib
adb pull system/lib/libui.so /proprietary/system/lib
adb pull system/lib/libservices.huawei.so /proprietary/system/lib
adb pull system/lib/libsurfaceflinger.so /proprietary/system/lib
adb pull system/lib/libHwMMITestCustEx_jni.so /proprietary/system/lib
adb pull system/lib/libhwlog_jni.so /proprietary/system/lib
adb pull system/lib/libCameraHwSendCmd.so /proprietary/system/lib
adb pull system/lib/libteec.so /proprietary/system/lib
adb pull system/lib/hw/audio.r_submix.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/gps47531.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/power.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/sensorhub.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/memtrack.hi3630.so /proprietary/system/lib/hw
adb pull system/lib/hw/copybit.hi3630.so /proprietary/system/lib/hw
adb pull system/lib/hw/audio.primary.hi3630.so /proprietary/system/lib/hw
adb pull system/lib/hw/gps4752.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/keystore.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/flp.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/nfc_nci.pn54x.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/local_time.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/fingerprint_module.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/gralloc.hi3630.so /proprietary/system/lib/hw
adb pull system/lib/hw/bluetooth.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/audio.primary.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/gps4752cl.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/lights.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/hwcomposer.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/gralloc.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/audio.a2dp.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/libbcmfm_if.so /proprietary/system/lib/hw
adb pull system/lib/hw/keystore.hi3630.so /proprietary/system/lib/hw
adb pull system/lib/hw/gps47531cl.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/audio_policy.default.so /proprietary/system/lib/hw
adb pull system/lib/hw/power.hi3630.so /proprietary/system/lib/hw
adb pull system/lib/hw/camera.hi3630.so /proprietary/system/lib/hw
adb pull system/lib/hw/vibrator.default.so /proprietary/system/lib/hw
adb pull system/isp/isp.bin /proprietary/system/isp
adb pull system/etc/modemConfig/lte_ue_msg.cfg /proprietary/system/etc/modemConfig
adb pull system/etc/modemConfig/viacbp82d_shutdown_log.bcfg /proprietary/system/etc/modemConfig
adb pull system/etc/modemConfig/viacbp82d_log.bcfg /proprietary/system/etc/modemConfig
adb pull system/etc/modemConfig/SystemCmd.cmf /proprietary/system/etc/modemConfig
adb pull system/etc/srs/srs_processing.cfg /proprietary/system/etc/srs
adb pull system/etc/srs/models.txt /proprietary/system/etc/srs
adb pull system/etc/srs/srsmodels.lic /proprietary/system/etc/srs
adb pull system/etc/camera/filter/mixIm.dat /proprietary/system/etc/camera/filter
adb pull system/etc/camera/filter/filter.xml /proprietary/system/etc/camera/filter
adb pull system/etc/camera/meitu/chengguang.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/qingse1.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/kujiu4.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/kujiu2.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/sucai4.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/overlayMap.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/dianying.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/PSScreen.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/sucai3.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/sucai5.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/moran.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/kujiu3.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/kujiu1.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/sucai7.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/meitu/kujiu5.mtdata /proprietary/system/etc/camera/meitu
adb pull system/etc/camera/hwscope/kernel /proprietary/system/etc/camera/hwscope
adb pull system/etc/camera/hwscope/hwsz.xml /proprietary/system/etc/camera/hwscope
adb pull system/etc/camera/tracking/targettracking.xml /proprietary/system/etc/camera/tracking
adb pull system/etc/camera/smartae/device.config /proprietary/system/etc/camera/smartae
adb pull system/etc/camera/smartae/s5k4e1gx_sunny/SmartAE.xml /proprietary/system/etc/camera/smartae/s5k4e1gx_sunny
adb pull system/etc/camera/smartae/s5k4e1ga_foxconn/SmartAE.xml /proprietary/system/etc/camera/smartae/s5k4e1ga_foxconn
adb pull system/etc/camera/smartae/ov5648_foxconn/SmartAE.xml /proprietary/system/etc/camera/smartae/ov5648_foxconn
adb pull system/etc/camera/smartae/sonyimx134_liteon/SmartAE.xml /proprietary/system/etc/camera/smartae/sonyimx134_liteon
adb pull system/etc/camera/smartae/ov5648_sunny/SmartAE.xml /proprietary/system/etc/camera/smartae/ov5648_sunny
adb pull system/etc/camera/smartae/s5k4e1gx_foxconn/SmartAE.xml /proprietary/system/etc/camera/smartae/s5k4e1gx_foxconn
adb pull system/etc/camera/smartae/sonyimx135_liteon/SmartAE.xml /proprietary/system/etc/camera/smartae/sonyimx135_liteon
adb pull system/etc/camera/smartae/imx214_foxconn/SmartAE.xml /proprietary/system/etc/camera/smartae/imx214_foxconn
adb pull system/etc/camera/smartae/imx214_sunny/SmartAE.xml /proprietary/system/etc/camera/smartae/imx214_sunny
adb pull system/etc/camera/smartae/sonyimx134_sunny/SmartAE.xml /proprietary/system/etc/camera/smartae/sonyimx134_sunny
adb pull system/etc/camera/tornado/SunsetModelTOA.model /proprietary/system/etc/camera/tornado
adb pull system/etc/camera/tornado/TornadoI.ini /proprietary/system/etc/camera/tornado
adb pull system/etc/camera/tornado/NightModelTOA.model /proprietary/system/etc/camera/tornado
adb pull system/etc/camera/tornado/SunsetMinMaxTOA.txt /proprietary/system/etc/camera/tornado
adb pull system/etc/camera/tornado/FoliageMinMaxTOA.txt /proprietary/system/etc/camera/tornado
adb pull system/etc/camera/tornado/FoliageModelTOA.model /proprietary/system/etc/camera/tornado
adb pull system/etc/camera/tornado/NightMinMaxTOA.txt /proprietary/system/etc/camera/tornado
adb pull system/etc/camera/tornado/sonyimx214_sunny/TornadoI.ini /proprietary/system/etc/camera/tornado/sonyimx214_sunny
adb pull system/etc/camera/tornado/sonyimx134_liteon/TornadoI.ini /proprietary/system/etc/camera/tornado/sonyimx134_liteon
adb pull system/etc/camera/tornado/sonyimx135_liteon/TornadoI.ini /proprietary/system/etc/camera/tornado/sonyimx135_liteon
adb pull system/etc/camera/tornado/imx214_foxconn/TornadoI.ini /proprietary/system/etc/camera/tornado/imx214_foxconn
adb pull system/etc/camera/tornado/sonyimx214_foxconn/TornadoI.ini /proprietary/system/etc/camera/tornado/sonyimx214_foxconn
adb pull system/etc/camera/tornado/imx214_sunny/TornadoI.ini /proprietary/system/etc/camera/tornado/imx214_sunny
adb pull system/etc/camera/tornado/sonyimx134_sunny/TornadoI.ini /proprietary/system/etc/camera/tornado/sonyimx134_sunny
adb pull system/etc/camera/soft3aconfig/device.config /proprietary/system/etc/camera/soft3aconfig
adb pull system/etc/camera/soft3aconfig/s5k4e1gx_sunny/soft3Aconfig.xml /proprietary/system/etc/camera/soft3aconfig/s5k4e1gx_sunny
adb pull system/etc/camera/soft3aconfig/s5k4e1ga_foxconn/soft3Aconfig.xml /proprietary/system/etc/camera/soft3aconfig/s5k4e1ga_foxconn
adb pull system/etc/camera/soft3aconfig/ov5648_foxconn/soft3Aconfig.xml /proprietary/system/etc/camera/soft3aconfig/ov5648_foxconn
adb pull system/etc/camera/soft3aconfig/sonyimx134_liteon/soft3Aconfig.xml /proprietary/system/etc/camera/soft3aconfig/sonyimx134_liteon
adb pull system/etc/camera/soft3aconfig/sonyimx135_liteon/soft3Aconfig.xml /proprietary/system/etc/camera/soft3aconfig/sonyimx135_liteon
adb pull system/etc/camera/soft3aconfig/imx214_foxconn/soft3Aconfig.xml /proprietary/system/etc/camera/soft3aconfig/imx214_foxconn
adb pull system/etc/camera/soft3aconfig/imx214_sunny/soft3Aconfig.xml /proprietary/system/etc/camera/soft3aconfig/imx214_sunny
adb pull system/etc/camera/soft3aconfig/sonyimx134_sunny/soft3Aconfig.xml /proprietary/system/etc/camera/soft3aconfig/sonyimx134_sunny
adb pull system/etc/camera/multidenoise/multidenoise.xml /proprietary/system/etc/camera/multidenoise
adb pull system/etc/camera/multidenoise/device.config /proprietary/system/etc/camera/multidenoise
adb pull system/etc/camera/multidenoise/s5k4e1ga_foxconn/imgproc.xml /proprietary/system/etc/camera/multidenoise/s5k4e1ga_foxconn
adb pull system/etc/camera/multidenoise/sonyimx134_liteon/imgproc.xml /proprietary/system/etc/camera/multidenoise/sonyimx134_liteon
adb pull system/etc/camera/multidenoise/sonyimx134_liteon/multiframe.xml /proprietary/system/etc/camera/multidenoise/sonyimx134_liteon
adb pull system/etc/camera/multidenoise/sonyimx135_liteon/imgproc.xml /proprietary/system/etc/camera/multidenoise/sonyimx135_liteon
adb pull system/etc/camera/multidenoise/sonyimx135_liteon/multiframe.xml /proprietary/system/etc/camera/multidenoise/sonyimx135_liteon
adb pull system/etc/camera/multidenoise/hi542/imgproc.xml /proprietary/system/etc/camera/multidenoise/hi542
adb pull system/etc/camera/multidenoise/default/imgproc.xml /proprietary/system/etc/camera/multidenoise/default
adb pull system/etc/camera/multidenoise/default/multiframe.xml /proprietary/system/etc/camera/multidenoise/default
adb pull system/etc/camera/multidenoise/ov8830/imgproc.xml /proprietary/system/etc/camera/multidenoise/ov8830
adb pull system/etc/camera/multidenoise/sonyimx134_sunny/imgproc.xml /proprietary/system/etc/camera/multidenoise/sonyimx134_sunny
adb pull system/etc/camera/multidenoise/sonyimx134_sunny/multiframe.xml /proprietary/system/etc/camera/multidenoise/sonyimx134_sunny
adb pull system/etc/camera/bshutter/device.config /proprietary/system/etc/camera/bshutter
adb pull system/etc/camera/bshutter/imx214/algo.xml /proprietary/system/etc/camera/bshutter/imx214
adb pull system/etc/camera/bshutter/imx214/info.xml /proprietary/system/etc/camera/bshutter/imx214
adb pull system/etc/camera/bshutter/default/algo.xml /proprietary/system/etc/camera/bshutter/default
adb pull system/etc/camera/bshutter/default/info.xml /proprietary/system/etc/camera/bshutter/default
adb pull system/etc/camera/davinci/device.config /proprietary/system/etc/camera/davinci
adb pull system/etc/camera/davinci/s5k4e1gx_sunny/imgproc.xml /proprietary/system/etc/camera/davinci/s5k4e1gx_sunny
adb pull system/etc/camera/davinci/s5k4e1ga_foxconn/imgproc.xml /proprietary/system/etc/camera/davinci/s5k4e1ga_foxconn
adb pull system/etc/camera/davinci/s5k4e1ga_foxconn/cm_foliage.dat /proprietary/system/etc/camera/davinci/s5k4e1ga_foxconn
adb pull system/etc/camera/davinci/ov5648_foxconn/imgproc.xml /proprietary/system/etc/camera/davinci/ov5648_foxconn
adb pull system/etc/camera/davinci/sonyimx134_liteon/cm_foliage_s.dat /proprietary/system/etc/camera/davinci/sonyimx134_liteon
adb pull system/etc/camera/davinci/sonyimx134_liteon/imgproc.xml /proprietary/system/etc/camera/davinci/sonyimx134_liteon
adb pull system/etc/camera/davinci/sonyimx134_liteon/cm_sky.dat /proprietary/system/etc/camera/davinci/sonyimx134_liteon
adb pull system/etc/camera/davinci/sonyimx134_liteon/multiframe.xml /proprietary/system/etc/camera/davinci/sonyimx134_liteon
adb pull system/etc/camera/davinci/sonyimx134_liteon/cm_sky_s.dat /proprietary/system/etc/camera/davinci/sonyimx134_liteon
adb pull system/etc/camera/davinci/sonyimx134_liteon/cm_normal.dat /proprietary/system/etc/camera/davinci/sonyimx134_liteon
adb pull system/etc/camera/davinci/sonyimx134_liteon/cm_foliage.dat /proprietary/system/etc/camera/davinci/sonyimx134_liteon
adb pull system/etc/camera/davinci/sonyimx134_liteon/cm_normal_s.dat /proprietary/system/etc/camera/davinci/sonyimx134_liteon
adb pull system/etc/camera/davinci/sonyimx134_liteon/cm_sunset.dat /proprietary/system/etc/camera/davinci/sonyimx134_liteon
adb pull system/etc/camera/davinci/ov5648_sunny/imgproc.xml /proprietary/system/etc/camera/davinci/ov5648_sunny
adb pull system/etc/camera/davinci/s5k4e1gx_foxconn/imgproc.xml /proprietary/system/etc/camera/davinci/s5k4e1gx_foxconn
adb pull system/etc/camera/davinci/sonyimx135_liteon/cm_foliage_s.dat /proprietary/system/etc/camera/davinci/sonyimx135_liteon
adb pull system/etc/camera/davinci/sonyimx135_liteon/imgproc.xml /proprietary/system/etc/camera/davinci/sonyimx135_liteon
adb pull system/etc/camera/davinci/sonyimx135_liteon/cm_sky.dat /proprietary/system/etc/camera/davinci/sonyimx135_liteon
adb pull system/etc/camera/davinci/sonyimx135_liteon/multiframe.xml /proprietary/system/etc/camera/davinci/sonyimx135_liteon
adb pull system/etc/camera/davinci/sonyimx135_liteon/cm_sky_s.dat /proprietary/system/etc/camera/davinci/sonyimx135_liteon
adb pull system/etc/camera/davinci/sonyimx135_liteon/cm_normal.dat /proprietary/system/etc/camera/davinci/sonyimx135_liteon
adb pull system/etc/camera/davinci/sonyimx135_liteon/cm_foliage.dat /proprietary/system/etc/camera/davinci/sonyimx135_liteon
adb pull system/etc/camera/davinci/sonyimx135_liteon/cm_normal_s.dat /proprietary/system/etc/camera/davinci/sonyimx135_liteon
adb pull system/etc/camera/davinci/sonyimx135_liteon/cm_sunset.dat /proprietary/system/etc/camera/davinci/sonyimx135_liteon
adb pull system/etc/camera/davinci/imx214_foxconn/cm_foliage_s.dat /proprietary/system/etc/camera/davinci/imx214_foxconn
adb pull system/etc/camera/davinci/imx214_foxconn/imgproc.xml /proprietary/system/etc/camera/davinci/imx214_foxconn
adb pull system/etc/camera/davinci/imx214_foxconn/cm_sky.dat /proprietary/system/etc/camera/davinci/imx214_foxconn
adb pull system/etc/camera/davinci/imx214_foxconn/multiframe.xml /proprietary/system/etc/camera/davinci/imx214_foxconn
adb pull system/etc/camera/davinci/imx214_foxconn/cm_sky_s.dat /proprietary/system/etc/camera/davinci/imx214_foxconn
adb pull system/etc/camera/davinci/imx214_foxconn/cm_normal.dat /proprietary/system/etc/camera/davinci/imx214_foxconn
adb pull system/etc/camera/davinci/imx214_foxconn/cm_foliage.dat /proprietary/system/etc/camera/davinci/imx214_foxconn
adb pull system/etc/camera/davinci/imx214_foxconn/cm_normal_s.dat /proprietary/system/etc/camera/davinci/imx214_foxconn
adb pull system/etc/camera/davinci/imx214_foxconn/cm_sunset.dat /proprietary/system/etc/camera/davinci/imx214_foxconn
adb pull system/etc/camera/davinci/hi542/imgproc.xml /proprietary/system/etc/camera/davinci/hi542
adb pull system/etc/camera/davinci/hi542/cm_foliage.dat /proprietary/system/etc/camera/davinci/hi542
adb pull system/etc/camera/davinci/default/cm_correction.dat /proprietary/system/etc/camera/davinci/default
adb pull system/etc/camera/davinci/default/imgproc.xml /proprietary/system/etc/camera/davinci/default
adb pull system/etc/camera/davinci/default/cm_sky.dat /proprietary/system/etc/camera/davinci/default
adb pull system/etc/camera/davinci/default/cm_normal.dat /proprietary/system/etc/camera/davinci/default
adb pull system/etc/camera/davinci/default/cm_foliage.dat /proprietary/system/etc/camera/davinci/default
adb pull system/etc/camera/davinci/default/cm_sunset.dat /proprietary/system/etc/camera/davinci/default
adb pull system/etc/camera/davinci/ov8830/imgproc.xml /proprietary/system/etc/camera/davinci/ov8830
adb pull system/etc/audio/dts/ascend_dts_algo_MOGOLIA_ULCA_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_JAZZ_CLG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_JAZZ_TLG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_PINE_TLG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_JAZZ_SGLTEU_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_PINE_ULG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_BELLA_CLG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_BELLA_TLGULG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_default_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_MOGOLIA_ULG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_PINE_CLG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_PINE_TLGULG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_BELLA_ULG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_JAZZ_ULG_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_JAZZ_ULCA_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/dts/ascend_dts_algo_MOGOLIA_TL_normal.xml /proprietary/system/etc/audio/dts
adb pull system/etc/audio/algorithm/algorithm_MOGOLIA_ULG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_JAZZ_TLG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_BELLA_TLGULG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_default_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_JAZZ_CLG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_JAZZ_SGLTEU_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_PINE_CLG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_MOGOLIA_TL_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_BELLA_CLG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_PINE_ULG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_PINE_TLG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_JAZZ_ULCA_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_PINE_TLGULG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_BELLA_ULG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_MOGOLIA_ULCA_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_FIFA_CLG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/algorithm/algorithm_JAZZ_ULG_normal.xml /proprietary/system/etc/audio/algorithm
adb pull system/etc/audio/tfa9887/tfa9887_feature.config /proprietary/system/etc/audio/tfa9887
adb pull system/etc/audio/tfa9887/coldboot.patch /proprietary/system/etc/audio/tfa9887
adb pull system/etc/audio/tfa9887/tfa9887_firmware.patch /proprietary/system/etc/audio/tfa9887
adb pull system/etc/audio/tfa9887/BELLA_ULG/dsp_coefficient.config /proprietary/system/etc/audio/tfa9887/BELLA_ULG
adb pull system/etc/audio/tfa9887/BELLA_ULG/speaker_model.speaker /proprietary/system/etc/audio/tfa9887/BELLA_ULG
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/incall_wb/incall_wb.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/incall_wb
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/incall_wb/incall_wb.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/incall_wb
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone/ringtone.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone/ringtone.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/voip/voip.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/voip
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/voip/voip.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/voip
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/incall_nb/incall_nb.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/incall_nb
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/incall_nb/incall_nb.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/incall_nb
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/music/music.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/music
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/music/music.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/music
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/fm/fm.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/fm
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/fm/fm.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/fm
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone_hs_spk/ringtone_hs_spk.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone_hs_spk/ringtone_hs_spk.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/bypass/bypass.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/bypass
adb pull system/etc/audio/tfa9887/BELLA_ULG/normal/bypass/bypass.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/bypass
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/incall_wb/incall_wb.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/incall_wb
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/incall_wb/incall_wb.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/incall_wb
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone/ringtone.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone/ringtone.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/voip/voip.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/voip
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/voip/voip.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/voip
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/incall_nb/incall_nb.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/incall_nb
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/incall_nb/incall_nb.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/incall_nb
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/music/music.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/music
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/music/music.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/music
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/fm/fm.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/fm
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/fm/fm.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/fm
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone_hs_spk/ringtone_hs_spk.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone_hs_spk/ringtone_hs_spk.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/bypass/bypass.eq /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/bypass
adb pull system/etc/audio/tfa9887/BELLA_ULG/ce/bypass/bypass.preset /proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/bypass
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/dsp_coefficient.config /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/speaker_model.speaker /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_wb/incall_wb.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_wb
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_wb/incall_wb.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_wb
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone/ringtone.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone/ringtone.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/voip/voip.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/voip
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/voip/voip.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/voip
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_nb/incall_nb.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_nb
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_nb/incall_nb.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_nb
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/music/music.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/music
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/music/music.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/music
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/fm/fm.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/fm
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/fm/fm.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/fm
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone_hs_spk/ringtone_hs_spk.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone_hs_spk/ringtone_hs_spk.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/bypass/bypass.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/bypass
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/normal/bypass/bypass.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/bypass
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_wb/incall_wb.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_wb
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_wb/incall_wb.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_wb
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone/ringtone.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone/ringtone.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/voip/voip.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/voip
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/voip/voip.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/voip
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_nb/incall_nb.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_nb
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_nb/incall_nb.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_nb
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/music/music.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/music
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/music/music.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/music
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/fm/fm.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/fm
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/fm/fm.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/fm
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone_hs_spk/ringtone_hs_spk.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone_hs_spk/ringtone_hs_spk.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/bypass/bypass.eq /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/bypass
adb pull system/etc/audio/tfa9887/BELLA_TLGULG/ce/bypass/bypass.preset /proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/bypass
adb pull system/etc/audio/tfa9887/default/dsp_coefficient.config /proprietary/system/etc/audio/tfa9887/default
adb pull system/etc/audio/tfa9887/default/speaker_model.speaker /proprietary/system/etc/audio/tfa9887/default
adb pull system/etc/audio/tfa9887/default/normal/incall_wb/incall_wb.eq /proprietary/system/etc/audio/tfa9887/default/normal/incall_wb
adb pull system/etc/audio/tfa9887/default/normal/incall_wb/incall_wb.preset /proprietary/system/etc/audio/tfa9887/default/normal/incall_wb
adb pull system/etc/audio/tfa9887/default/normal/ringtone/ringtone.preset /proprietary/system/etc/audio/tfa9887/default/normal/ringtone
adb pull system/etc/audio/tfa9887/default/normal/ringtone/ringtone.eq /proprietary/system/etc/audio/tfa9887/default/normal/ringtone
adb pull system/etc/audio/tfa9887/default/normal/voip/voip.preset /proprietary/system/etc/audio/tfa9887/default/normal/voip
adb pull system/etc/audio/tfa9887/default/normal/voip/voip.eq /proprietary/system/etc/audio/tfa9887/default/normal/voip
adb pull system/etc/audio/tfa9887/default/normal/incall_nb/incall_nb.eq /proprietary/system/etc/audio/tfa9887/default/normal/incall_nb
adb pull system/etc/audio/tfa9887/default/normal/incall_nb/incall_nb.preset /proprietary/system/etc/audio/tfa9887/default/normal/incall_nb
adb pull system/etc/audio/tfa9887/default/normal/music/music.preset /proprietary/system/etc/audio/tfa9887/default/normal/music
adb pull system/etc/audio/tfa9887/default/normal/music/music.eq /proprietary/system/etc/audio/tfa9887/default/normal/music
adb pull system/etc/audio/tfa9887/default/normal/fm/fm.preset /proprietary/system/etc/audio/tfa9887/default/normal/fm
adb pull system/etc/audio/tfa9887/default/normal/fm/fm.eq /proprietary/system/etc/audio/tfa9887/default/normal/fm
adb pull system/etc/audio/tfa9887/default/normal/ringtone_hs_spk/ringtone_hs_spk.preset /proprietary/system/etc/audio/tfa9887/default/normal/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/default/normal/ringtone_hs_spk/ringtone_hs_spk.eq /proprietary/system/etc/audio/tfa9887/default/normal/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/default/normal/bypass/bypass.eq /proprietary/system/etc/audio/tfa9887/default/normal/bypass
adb pull system/etc/audio/tfa9887/default/normal/bypass/bypass.preset /proprietary/system/etc/audio/tfa9887/default/normal/bypass
adb pull system/etc/audio/tfa9887/default/ce/incall_wb/incall_wb.eq /proprietary/system/etc/audio/tfa9887/default/ce/incall_wb
adb pull system/etc/audio/tfa9887/default/ce/incall_wb/incall_wb.preset /proprietary/system/etc/audio/tfa9887/default/ce/incall_wb
adb pull system/etc/audio/tfa9887/default/ce/ringtone/ringtone.preset /proprietary/system/etc/audio/tfa9887/default/ce/ringtone
adb pull system/etc/audio/tfa9887/default/ce/ringtone/ringtone.eq /proprietary/system/etc/audio/tfa9887/default/ce/ringtone
adb pull system/etc/audio/tfa9887/default/ce/voip/voip.preset /proprietary/system/etc/audio/tfa9887/default/ce/voip
adb pull system/etc/audio/tfa9887/default/ce/voip/voip.eq /proprietary/system/etc/audio/tfa9887/default/ce/voip
adb pull system/etc/audio/tfa9887/default/ce/incall_nb/incall_nb.eq /proprietary/system/etc/audio/tfa9887/default/ce/incall_nb
adb pull system/etc/audio/tfa9887/default/ce/incall_nb/incall_nb.preset /proprietary/system/etc/audio/tfa9887/default/ce/incall_nb
adb pull system/etc/audio/tfa9887/default/ce/music/music.preset /proprietary/system/etc/audio/tfa9887/default/ce/music
adb pull system/etc/audio/tfa9887/default/ce/music/music.eq /proprietary/system/etc/audio/tfa9887/default/ce/music
adb pull system/etc/audio/tfa9887/default/ce/fm/fm.preset /proprietary/system/etc/audio/tfa9887/default/ce/fm
adb pull system/etc/audio/tfa9887/default/ce/fm/fm.eq /proprietary/system/etc/audio/tfa9887/default/ce/fm
adb pull system/etc/audio/tfa9887/default/ce/ringtone_hs_spk/ringtone_hs_spk.preset /proprietary/system/etc/audio/tfa9887/default/ce/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/default/ce/ringtone_hs_spk/ringtone_hs_spk.eq /proprietary/system/etc/audio/tfa9887/default/ce/ringtone_hs_spk
adb pull system/etc/audio/tfa9887/default/ce/bypass/bypass.eq /proprietary/system/etc/audio/tfa9887/default/ce/bypass
adb pull system/etc/audio/tfa9887/default/ce/bypass/bypass.preset /proprietary/system/etc/audio/tfa9887/default/ce/bypass
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_MOGOLIA_TL_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_MOGOLIA_ULCA_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_ULG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_ULG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_BELLA_TLGULG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_SGLTEU_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_TLGULG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_default_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_ULCA_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_CLG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_BELLA_ULG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_MOGOLIA_ULG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_TLG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_TLG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_BELLA_CLG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_CLG_normal.xml /proprietary/system/etc/audio/mbdrc
adb pull system/etc/audio/modem/ascend_modem_algo_PINE_ULG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_MOGOLIA_ULCA_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_JAZZ_ULG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_BELLA_TLGULG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_JAZZ_SGLTEU_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_PINE_TLGULG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_PINE_CLG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_BELLA_CLG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_JAZZ_TLG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_JAZZ_ULCA_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_JAZZ_CLG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_default_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_MOGOLIA_ULG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_BELLA_ULG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_PINE_TLG_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/modem/ascend_modem_algo_MOGOLIA_TL_normal.xml /proprietary/system/etc/audio/modem
adb pull system/etc/audio/codec/ascend_BELLA_ULG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_FIFA_CLG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_BELLA_CLG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_PINE_TLGULG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_default_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_ULCA_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_TLG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_CLG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_CLG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_ULG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_BELLA_ULG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_MOGOLIA_TL_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_PINE_TLGULG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_PINE_TLG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_MOGOLIA_ULG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_PINE_CLG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_PINE_TLG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_MOGOLIA_ULCA_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_MOGOLIA_TL_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_MOGOLIA_ULG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_MOGOLIA_ULCA_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_PINE_CLG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_TLG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_BELLA_CLG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_SGLTEU_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_ULCA_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_SGLTEU_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_PINE_ULG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_BELLA_TLGULG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_FIFA_CLG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_JAZZ_ULG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_PINE_ULG_normal.xml /proprietary/system/etc/audio/codec
adb pull system/etc/audio/codec/ascend_BELLA_TLGULG_ce.xml /proprietary/system/etc/audio/codec
adb pull system/vendor/lib/egl/libGLES_mali.so /proprietary/system/vendor/lib/egl
adb pull system/vendor/lib/hw/hwcomposer.hi3630.so /proprietary/system/vendor/lib/hw
adb pull system/vendor/firmware/libpn547_fw.so /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/BCM4334B0_002.001.013.1164.1457_RC.hcd /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_mogolia_ulca.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_pine_tlg.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_dualband.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_pine_clg.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_mogolia_tl.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_jazz_clg.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/fw_bcm4334_hw_dualband.bin /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/fw_bcm4334_test_hw_apsta_dualband.bin /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_jazz_ulg.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/fw_bcm4334_apsta_hw_dualband.bin /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_jazz_ulca.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_jazz_tlg.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_mogolia_ulg.txt /proprietary/system/vendor/firmware
adb pull system/vendor/firmware/nvram4334_hw_pine_ulgtlg.txt /proprietary/system/vendor/firmware
adb pull system/vendor/framework/com.huawei.audioalgo.jar /proprietary/system/vendor/framework
adb pull system/vendor/etc/audio_effects.conf /proprietary/system/vendor/etc


# Total 442 files added on 2015-10-25T13:25:23.115586 UTC
